version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: docker.io/mongo:4.4.9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=4dm1nspN3w
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=0nly4dm1nspN3w
    networks: 
      - wifi
    ports:
      - '27017:27017'
    volumes: 
      - ./mongo-volume:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks: 
      - wifi
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=4dm1nspN3w
      - ME_CONFIG_MONGODB_ADMINPASSWORD=0nly4dm1nspN3w
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - '8081:8081'
    volumes: 
      - ./mongo-expres:/data/db   

networks:
  wifi:
    driver: bridge
