version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks: 
      - wifi
    ports:
      - '27017:27017'
    volumes: 
      - ./database:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks: 
      - wifi
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - '8081:8081'
    volumes: 
      - ./database:/data/db      

networks:
  wifi:
    driver: bridge
